main_controller=require('./../controller/main_controller')
module.exports=(app)=>{
    app.get('/',(req,res)=>{
        main_controller.index(req,res)
    })
    app.post('/',(req,res)=>{
        main_controller.info(req,res)
    })
    app.get('/result',(req,res)=>{
        main_controller.result(req,res)
    })
}